### ISSUE TITLE
Can't save Address Fieldtype

### ISSUE THREAD

**Issue by rjgux** [doublesecretagency/craft-smartmap#37] opened 2019-03-08 16:42 UTC
Whenever I try and save an entry with a Smartmap Address field type I get the following error -

`Getting unknown property: doublesecretagency\smartmap\models\Address::save`

- Smart map version 3.2.1
- Craft version 3.1.16

**Full stack trace** -

```
yii\base\UnknownPropertyException: Getting unknown property: doublesecretagency\smartmap\models\Address::save in /Users/rich/git/axter/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /Users/rich/git/axter/vendor/yiisoft/yii2/base/Model.php(1026): yii\base\Component->__get('save')
#1 /Users/rich/git/axter/vendor/doublesecretagency/craft-smartmap/src/services/SmartMapService.php(369): yii\base\Model->offsetGet('save')
#2 /Users/rich/git/axter/vendor/doublesecretagency/craft-smartmap/src/fields/Address.php(97): doublesecretagency\smartmap\services\SmartMapService->saveAddressField(Object(doublesecretagency\smartmap\fields\Address), Object(craft\elements\Entry))
#3 /Users/rich/git/axter/vendor/craftcms/cms/src/base/Element.php(1882): doublesecretagency\smartmap\fields\Address->afterElementSave(Object(craft\elements\Entry), false)
#4 /Users/rich/git/axter/vendor/craftcms/cms/src/elements/Entry.php(1151): craft\base\Element->afterSave(false)
#5 /Users/rich/git/axter/vendor/craftcms/cms/src/services/Elements.php(515): craft\elements\Entry->afterSave(false)
#6 /Users/rich/git/axter/vendor/craftcms/cms/src/controllers/EntriesController.php(549): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#7 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#8 /Users/rich/git/axter/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /Users/rich/git/axter/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /Users/rich/git/axter/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('save-entry', Array)
#11 /Users/rich/git/axter/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#12 /Users/rich/git/axter/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('entries/save-en...', Array)
#13 /Users/rich/git/axter/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('entries/save-en...', Array)
#14 /Users/rich/git/axter/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#15 /Users/rich/git/axter/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /Users/rich/git/axter/public/index.php(23): yii\base\Application->run()
#17 /Users/rich/.composer/vendor/laravel/valet/server.php(151): require('/Users/rich/git...')
#18 {main}
```

**Comment by lindseydiloreto** [comment] 2019-03-08 18:38
Hmm, that's very odd. This was reported one other time recently, but we weren't able to get to the bottom of it.

Can you ping me on [Craft Discord](https://craftcms.com/discord) so we can troubleshoot it together?

**Comment by lindseydiloreto** [comment] 2019-03-13 18:36
After chatting with you on Discord, it sounds like we're not able to reproduce this problem. At this point, it's still very much a mystery.

I'll leave this ticket open a bit longer, and try to do some testing on Craft 3.1 specifically. If I still come up empty-handed after that, we'll just have to close this thread and move on.

Thanks again for reporting it, let me know if any new information comes up!

**Closed as completed** 2020-03-02 04:55 UTC
Labels: requires 3.1

**Comment by lindseydiloreto** [comment] 2020-06-10 20:57
Just chased this ghost around with another user... it looks like there's some sort of conflict with an older PHP version. Using a more recent version of PHP did the trick.

For anyone dealing with this in the future, **switch to PHP 7.4** and see if that resolves the issue.
